#!/bin/bash

## Install the pre-compiled mtasc binary and support
## folders for Ubuntu 14.04 installations.

GIT_REPO=https://github.com/develephant/mtasc.git
BIN_VER=mtasc-bin-ubuntu-14.04
SRC_DIR=/usr/local/src
DST_DIR=/usr/local/bin

clear

echo ''
echo "Freshening up..."
echo ''

apt-get update && apt-get install -y \
  figlet \
  git

clear

figlet 'MTASC'
echo '--== Compiled for Ubuntu 14.04 ==--'

echo ''
echo 'Press any key to install:'
read

cd $SRC_DIR

git clone $GIT_REPO

cd mtasc/builds

tar xvf ${BIN_VER}.tar

cp -R ${BIN_VER}/* $DST_DIR

rm -rf ${SRC_DIR}/mtasc

ls -l $DST_DIR

clear

figlet 'MTASC Ready'

echo '--== You can find the mtasc binary in /usr/local/bin ==--'
echo ''

mtasc

rm /root/setup-*

exit 0
