#!/bin/bash

yum update

yum groupinstall 'Development Tools'

yum install \
  pcre pcre-devel \
  ruby ruby-devel \
  rubygem-rake \
  zlib zlib-devel \
  wget

# Working DIR
cd /usr/local/src

# Git source
git clone https://github.com/develephant/mtasc.git

# Move to source dir
cd mtasc

# Start tools setup
rake setup

# Install
rake install

#Bye
echo 'All Done!'

exit 0