#!/bin/bash

## Compile MTASC 1.15 Ubuntu/Debian
## GNU/Linux

#Clean?
if [ "$1" == 'clean' ]; then
  rm -rf /usr/local/src/*
  rm /usr/local/bin/mtasc
  rm -rf /use/local/bin/std*
fi

# Update repos
apt-get update

# Install tools
apt-get install -y \
  build-essential \
  curl \
  git \
  libpcre3 \
  libpcre3-dev \
  m4 \
  rake \
  s3cmd \
  zlib1g \
  zlib1g-dev

# Working DIR
cd /usr/local/src

# Git source
git clone https://github.com/develephant/mtasc.git

# Move to source dir
cd mtasc

# Start tools setup
rake setup

# Install
rake install

exit 0
